### ISSUE TITLE
Current page is not always highlighted

### ISSUE THREAD

**Issue by penaeric** [alexgaribay/octoflat#10]
The current page is not highlighted (in green) when the page is a custom one and it was created with
rake new_page[about]

However, the current page is highlighted if it was created with
rake new_page[about.html]

Not a big issue, but it would be nice if you mention it on the documentation.

(also, a brief explanation of how the navigation works would be helpful)

Thanks for your work!

**Comment by alexgaribay** [comment]
I added more info about it to the readme
