### ISSUE TITLE
Categories page case sensitive. 

### ISSUE THREAD

**Issue by ehouse** [alexgaribay/octoflat#25]
Categories do not link correctly unless category is all lowercase. If category is not all lowercase it returns 404. 
Bug can be seen http://alexgaribay.com/blog/categories/iOS/

**Comment by alexgaribay** [comment]
Interesting. They work when I'm running it locally using 'rake preview'. I'll dig into it.

**Comment by seanicus** [comment]
I noticed the same thing...

**Comment by alexgaribay** [comment]
Latest commit fixes the issue.
