### ISSUE TITLE
Disqus Comment Count

### ISSUE THREAD

**Issue by seanicus** [alexgaribay/octoflat#26]
Hey Alex,

First of all, great theme!  I am having one problem, however... I can't seem to get the Disqus comment count on the blog index page to work. The disqus comments show up if I drill into the post... not sure what I'm doing wrong.  The site is

www.artifexcontramundum.com

Any idea what I've missed?

**Comment by yang2012** [comment]
I also encountered this problem. Any help??

**Comment by alexgaribay** [comment]
I don't believe this is an issue of the theme. I didn't modify how comment counts are handled. However, I did experience getting my own issues getting comment counts to work properly. But that was from my own configuration errors.

You may have to tinker with your _config.yml file and the link set on your Disqus settings, specifically the URL that both use.

**Comment by seanicus** [comment]
Apologies for falsely accusing octoflat:  it helps if you set 

disqus_show_comment_count

to true in _config.yml.  Ooops!

**Comment by alexgaribay** [comment]
It happens :)

**Comment by yang2012** [comment]
It works after I set disqus_show_comment_count be true. Thanks :)
