### ISSUE TITLE
Linkedin icon gone after updating octopress

### ISSUE THREAD

**Issue by tschoonj** [alexgaribay/octoflat#36]
Hi,

I noticed that the Linkedin icon has gone missing after updating octopress from my blog navbar. I guess it has to do with FontAwesome changing some of the identifiers of its icons?

Check out the problem at http://tschoonj.github.io/index.html

Cheers,

Tom

**Comment by ngocphamm** [comment]
Isn't it there on your navigation bar?

**Comment by tschoonj** [comment]
Interesting: the problem only seems to occur on Safari 6.0.3 on Mountain Lion. Firefox, Chrome Safari on Mavericks and iOS don't seem to have this problem.

I'll close it since it seems to be a browser issue, unrelated to octoflat and octopress.

Thanks for the comment!
