### ISSUE TITLE
Code highlighting is missing.

### ISSUE THREAD

**Issue by alexgaribay** [alexgaribay/octoflat#6]
Syntax highlighting of code is missing. Will be fixed by redoing the sass files to include the components required for syntax highlighting.

**Comment by davidcelis** [comment]
This is something that's currently stopping me from adopting the theme... That and codeblock line-gutters appear to be pretty severely messed up :frowning:

**Comment by alexgaribay** [comment]
I'm aware of the line gutters. I know it looks bad on mobile at the moment.
